Added Japanese language
LOOHP/InteractionVisualizerLanguages pull request #17
Opened 2023-10-20 11:36 UTC by ringo360

Japanese translation added.
> This translation includes additional explanations for parts of the default (en_US) explanation that were difficult to understand. (For example, the ProgressBarLength and Settings sections)

2023-10-20 12:18 UTC, takejohn requested changes
Nice translation!
However, I saw some typos. Please check them.

2023-10-20 12:18 UTC, takejohn commented on ja_JP/config.yml
> +#ItemStand は、アーマースタンドとアイテムフレームを使用するすべてのディスプレイを表します。
```suggestion
#ItemStand は、防具立てと額縁を使用するすべてのディスプレイを表します。
```
*armorstands*, *itemframes* は日本語版 Minecraft においてそれぞれ「防具立て」、「額縁」と呼ばれることが一般的です。

2023-10-20 12:18 UTC, takejohn commented on ja_JP/music.yml
> +  IRON_XYLOPHONE: 鉄筋
```suggestion
  IRON_XYLOPHONE: 鉄琴
```
typo: `鉄筋` -> `鉄琴`

2023-10-20 13:07 UTC, ringo360 commented on ja_JP/config.yml
> +#ItemStand は、アーマースタンドとアイテムフレームを使用するすべてのディスプレイを表します。
Thanks <3

2023-10-22 11:02 UTC, ringo360 commented
Please merge…

2024-01-06 23:32 UTC, merged